### ISSUE TITLE
Can this vscode theme be added to the godot theme?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [godotengine/godot-syntax-themes#12]
![noctisLux](https://user-images.githubusercontent.com/12076232/166127055-909758cf-bad4-4cd7-aebe-789c78dc8d5b.png)
![noctisHibernus](https://user-images.githubusercontent.com/12076232/166127056-7d082113-f365-49c9-8a8e-0a1dca752186.png)

https://github.com/liviuschera/noctis

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:

**Comment by Yakumo-Yukari** [comment]
> I won't work on this myself, but feel free to open a pull request for this 🙂

What is the format of the color codes in the tet file, they don't look like RGB or hexadecimal color codes, can you tell me how this color codes are converted? Thank you!

**Comment by Yakumo-Yukari** [comment]
> > What is the format of the color codes in the tet file, they don't look like RGB or hexadecimal color codes, can you tell me how this color codes are converted? Thank you!
> 
> Godot 3.x (`master` branch of this repository) uses ARGB color codes, while Godot 4.0alpha (`4.0-dev` branch of this repository) uses RGBA color codes.

thx
