### ISSUE TITLE
Make theme available for GDScript with Visual Studio Code

### ISSUE THREAD

**Issue by Arrow-x** [godotengine/godot-syntax-themes#7]
maybe help the original themes on Visual Studio Code work better with GDScript

**Comment by Calinou** [comment]
What do you mean? I already ported the Dark+ and Light+ themes from Visual Studio Code to Godot.

**Comment by Arrow-x** [comment]
the other way around, I know this out of scope for this, but may be for the Godot tools for VSCode, to make sure that themes there work with Godot's syntax

**Comment by Calinou** [comment]
I'm afraid we can't monkey-patch other people's themes in VS Code like that. Also, this is out of scope for this repository, so I'll close this.
